name: GitHub Actions Demo
on:
  push:
    paths:
      - packages/server/**
      - .github/workflows/demo.yaml

defaults:
  run:
    working-directory: packages/server

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm i --production
      - run: npm i esbuild -D
      - run: npm run build
      - run: npm i -g @serverless-devs/s
      - run: s config add --AccessKeyID ${{secrets.AccessKeyID}} --AccessKeySecret ${{secrets.AccessKeySecret}} -a default -f
      - run: s deploy -y --use-local
