name: GitHub Actions Demo
on:
  push:
    paths:
      - packages/server/**
      - '*.json'
      - '*.js'
      - .github/workflows/*.yaml

defaults:
  run:
    working-directory: packages/server

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls -l
      # - run: echo 'success'
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      
